
[env]
TERM = "xterm-256color"

[window]
decorations = "None"
padding = { x = 6, y = 4 }
dynamic_padding = true
dynamic_title = true

[font]
normal = { family = "FiraCode Nerd Font", style = "Regular" }
bold = { family = "FiraCode Nerd Font", style = "bold" }
italic = { family = "FiraCode Nerd Font", style = "italic" }
size = 10.5

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "On" }
blink_interval = 400
blink_timeout = 0

[mouse]
bindings = [
	{ mouse = "Right", action = "Paste" } 
]

[keyboard]
bindings = [
	{ key = "C", mods = "Control|Shift", action = "Copy" },
	{ key = "V", mods = "Control|Shift", action = "Paste" }
]

[general]
import = [
	"~/.config/alacritty/catppuccin-mocha.toml"
]

[terminal]
shell = "/bin/bash"
